apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ane7j1xsu-nodejs
  janus-idp.io/tekton: ane7j1xsu-nodejs
  backstage.io/kubernetes-id: ane7j1xsu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ane7j1xsu-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
