apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ane7j1xsu-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ane7j1xsu-nodejs 
  name: ane7j1xsu-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ane7j1xsu-nodejs 
